description: >
  Save composer cache.

parameters:
  enviroment:
    description: Select a specific enviroment.
    default: controlla
    type: string

steps:
  - save_cache:
      name: Cache composer dependencies
      key: composer-v1-{{ checksum "composer.lock" }}
      paths: /home/circleci/<<parameters.enviroment>>/vendor
